### ISSUE TITLE
Issue compiling not top lvl return statement.

### ISSUE THREAD

**Issue by martincousido** [norswap/sigh#1]
Lets say I have something like this:
`fun test (x: String) :String { 
          return x 
  } 
print(test("a"))`

Should print  `a`

But it actually fails with this error:

`java.lang.Error: unreachable
	at norswap.sigh.bytecode.TypeUtils.fieldDescriptor(TypeUtils.java:120)
	at norswap.sigh.bytecode.TypeUtils.asmType(TypeUtils.java:130)
	at norswap.sigh.bytecode.BytecodeCompiler.nodeAsmType(BytecodeCompiler.java:858)
	at norswap.sigh.bytecode.BytecodeCompiler.returnStmt(BytecodeCompiler.java:630)
`

This is because the type attribute should be retrieved from the expression on the return statement and not the statement node itself like it is done if it were a top level return.

**Comment by norswap** [comment]
Nice catch! 👍
